name: tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  unittest:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run test suite in the application image
        run: ./scripts/run_tests.sh
